apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zain-hotel-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: { { .Values.alb.scheme } }
    alb.ingress.kubernetes.io/target-type: { { .Values.alb.targetType } }
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn:
      { { .Values.alb.certificateArn } }
spec:
  rules:
    - host: { { .Values.domain } }
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: { { .Values.services.backend.name } }
                port:
                  number: { { .Values.services.backend.port } }

          - path: /
            pathType: Prefix
            backend:
              service:
                name: { { .Values.services.frontend.name } }
                port:
                  number: { { .Values.services.frontend.port } }
